# Generated by Django 4.0.5 on 2022-06-14 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование объекта')),
                ('type', models.CharField(choices=[(0, 'PROCEDURE'), (1, 'OBJECT'), (2, 'PACKAGE')], max_length=20, verbose_name='Тип')),
                ('date', models.DateField(verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Системный список',
                'verbose_name_plural': 'Системные списки',
            },
        ),
        migrations.CreateModel(
            name='FuncAcceptanceCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=255, verbose_name='Номер')),
                ('protocol', models.CharField(max_length=255, verbose_name='Протокол тестирования')),
                ('description', models.CharField(max_length=255, verbose_name='Описание патча')),
                ('date', models.DateField(verbose_name='Дата посадки')),
                ('customer', models.CharField(max_length=255, verbose_name='Заказчик')),
                ('executor', models.CharField(max_length=255, verbose_name='Исполнитель')),
                ('objects', models.ManyToManyField(blank=True, to='core.systemlist', verbose_name='Объекты')),
            ],
            options={
                'verbose_name': 'Функционально приёмочный акт',
                'verbose_name_plural': 'Функционально приёмочные акты',
            },
        ),
    ]
