# Generated by Django 4.0.5 on 2022-06-14 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_systemlist_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='funcacceptancecertificate',
            old_name='objects',
            new_name='objs',
        ),
    ]
