# Generated by Django 4.0.5 on 2022-06-15 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_objects_funcacceptancecertificate_objs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcacceptancecertificate',
            name='objs',
        ),
        migrations.AddField(
            model_name='funcacceptancecertificate',
            name='objs',
            field=models.TextField(blank=True, verbose_name='Объекты'),
        ),
    ]
